weights='/home/omen/Documents/Megha/FRACATLAS-FASTAPI/src/model_files/best.pt'
input_image_path=''
DICOM_TEMP_PATH='/home/omen/Documents/Megha/FRACATLAS-FASTAPI/DICOM_TEMP_PATH'
JPEG_TEMP_PATH='/home/omen/Documents/Megha/FRACATLAS-FASTAPI/JPEG_TEMP_PATH'
OutputDir = 'Outputs'